version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 mandrill_webhooks.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
